### ISSUE TITLE
bug(crate): sparrowdb 0.1.5 fails to compile — Catalog does not implement Clone

### ISSUE THREAD

**Issue by ryaker** [ryaker/SparrowDB#218]
## Bug

`sparrowdb` 0.1.5 fails to compile when used as a dependency. Reported by SparrowOntology when bumping from 0.1.2 → 0.1.5.

## Error

```
error[E0599]: no method named `clone` found for struct `std::sync::RwLockReadGuard<'_, Catalog>`
   --> sparrowdb-0.1.5/src/lib.rs:420:14
    |
416 | /         self.inner
417 | |             .catalog
418 | |             .read()
419 | |             .expect("catalog RwLock poisoned")
420 | |             .clone()
    |             -^^^^^ method not found in `RwLockReadGuard<'_, Catalog>`
```

## Root Cause

`Catalog` does not implement `Clone`. Calling `.clone()` on the `RwLockReadGuard` requires the inner type to be `Clone` for deref coercion to apply.

## Fix Options

1. Add `#[derive(Clone)]` to `Catalog` (if deep-clone is safe/correct)
2. Dereference and clone explicitly: `(*guard).clone()` (same requirement)
3. Restructure `lib.rs:420` to not clone the guard — return a projection instead

## Impact

SparrowOntology is pinned back to 0.1.2 until this is fixed, missing:
- UNIQUE constraint fixes (SPA-234/235)
- WAL/Catalog/PropertyIndex persistence
- Int-0 null fix (SPA-207 / PR #215)

## Reported By

SparrowOntology agent via agent-bus (#65)
